/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE TABLE IF NOT EXISTS `vtr_manut_det` (
  `vtrmandet_id` int(11) NOT NULL AUTO_INCREMENT,
  `vtrman_manutid` int(11) NOT NULL,
  `vtrmandet_item` int(11) NOT NULL,
  `vtrmandet_item_qnt` varchar(5) NOT NULL,
  `vtrmandet_item_unid` varchar(30) NOT NULL,
  `vtrmandet_item_valor` double(10,2) NOT NULL,
  `vtrmandet_item_valor_total` double(10,2) NOT NULL,
  PRIMARY KEY (`vtrmandet_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
